const BOOKS = [
    'The 5 Love Languages: The Secret to Love that Lasts by Gary D. Chapman',
    'The 7 Day Startup: You Don’t Learn Until You Launch by Dan Norris',
    'The 22 Immutable Laws of Branding by Al Ries and Laura Ries',
    'The 22 Immutable Laws of Marketing by Al Ries and Jack Trout',
    'The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change by Stephen R. Covey',
    '59 Seconds: Think a Little, Change a Lot by Richard Wiseman',
    '100 Great Copywriting Ideas by Andy Maslen',
    '100 Ways to Improve Your Writing by Gary Provost',
    'The Adweek Copywriting Handbook: The Ultimate Guide to Writing Powerful Advertising and Marketing Copy from One of America’s Top Copywriters by Joseph Sugarman',
    'The Almanack of Naval Ravikant: A Guide to Wealth and Happiness by Eric Jorgenson',
    'A Guide to the Good Life: The Ancient Art of Stoic Joy by William B. Irvine',
    'A Manual for Living by Epictetus',
    'An Astronaut’s Guide to Life on Earth: What Going to Space Taught Me About Ingenuity, Determination, and Being Prepared for Anything by Chris Hadfield',
    'Anything You Want: 40 Lessons for a New Kind of Entrepreneur by Derek Sivers',
    'The Art of Work: A Proven Path to Discovering What You Were Meant to Do by Jeff Goins',
    'Atomic Habits: Tiny Changes, Remarkable Results by James Clear',
    'Awaken The Giant Within: How to Take Immediate Control of Your Mental, Emotional, Physical and Financial Destiny! by Anthony Robbins',
    'Become an Idea Machine: Because Ideas Are The Currency Of The 21st Century by Claudia Azula Altucher',
    'Better Than Before: Mastering The Habits of Our Everyday Lives by Gretchen Rubin',
    'Beyond Basketball: Coach K’s Keywords for Success by Mike Krzyzewski, Jamie K. Spatola',
    'Bigger Leaner Stronger: The Simple Science of Building the Ultimate Male Body (Third Edition) by Michael Matthews',
    'Black Box Thinking: The Surprising Truth About Success by Matthew Syed',
    'The Brand Gap: How to Bridge the Distance Between Business Strategy and Design by Marty Neumeier',
    'Bounce: The Myth of Talent and the Power of Practice by Matthew Syed',
    'Built to Sell: Creating a Business That Can Thrive Without You by John Warrillow',
    'Building a Second Brain: A Proven Method to Organize Your Digital Life and Unlock Your Creative Potential by Tiago Forte',
    'Building a StoryBrand: Clarify Your Message So Customers Will Listen by Donald Miller',
    'Can’t Hurt Me: Master Your Mind and Defy the Odds by David Goggins',
    'Calmer, Easier, Happier Parenting: Five Strategies That End the Daily Battles and Get Kids to Listen the First Time by Noël Janis-Norton',
    'The Checklist Manifesto: How To Get Things Right by Atul Gawande',
    'Choose Yourself: Be Happy, Make Millions, Live The Dream! by James Altucher',
    'The Choose Yourself Guide to Wealth by James Altucher',
    'Contagious: Why Things Catch On by Jonah Berger',
    'The Copywriter’s Handbook: A Step-By-Step Guide To Writing Copy That Sells by Robert W. Bly',
    'Create or Hate: Successful People Make Things by Dan Norris',
    'The Daily Stoic: 366 Meditations on Wisdom, Perseverance, and the Art of Living by Ryan Holiday',
    'Decisive: How to Make Better Choices in Life by Chip Heath and Dan Heath',
    'Deep Work: Rules for Focused Success in a Distracted World by Cal Newport',
    'Digital Minimalism: Choosing a Focused Life in a Noisy World by Cal Newport',
    'The Dip: The Extraordinary Benefits of Knowing When to Quit (and When to Stick) by Seth Godin',
    'Do The Work: Overcome Resistance and Get Out of Your Own Way by Steven Pressfield',
    'Don’t Give Up, Don’t Give In: Life Lessons from an Extraordinary Man by Louis Zamperini',
    'Drive: The Surprising Truth About What Motivates Us by Daniel H. Pink',
    'The E-Myth Revisited: Why Most Small Businesses Don’t Work and What to Do About It by Michael E. Gerber',
    'Eat That Frog! Get More of the Important Things Done – Today! by Brian Tracy',
    'Effortless: Make It Easier to Do What Matters Most by Greg McKeown',
    'Ego Is the Enemy: The Fight to Master Our Greatest Opponent by Ryan Holiday',
    'Essential Zen Habits: Mastering The Art of Change, Briefly by Leo Babauta',
    'Essentialism: The Disciplined Pursuit of Less by Greg McKeown',
    'Factfulness: Ten Reasons We’re Wrong About the World—and Why Things Are Better Than You Think by Hans Rosling',
    'Feeling Good: The New Mood Therapy by David D. Burns',
    'Feeling Great: The Revolutionary New Treatment for Depression and Anxiety by David D. Burns',
    'The Gap and The Gain: The High Achievers’ Guide to Happiness, Confidence, and Success by Benjamin Hardy',
    'Getting Things Done: The Art of Stress-Free Productivity by David Allen',
    'The Good Life Handbook by Epictetus',
    'Grit: The Power of Passion and Perseverance by Angela Duckworth',
    'Hack the Entrepreneur: How to Stop Procrastinating, Build a Business, and Do Work That Matters by Jon Nastor',
    'Hell Yeah or No: What’s Worth Doing by Derek Sivers',
    'The Happiness Advantage: The Seven Principles of Positive Psychology that Fuel Success and Performance at Work by Shawn Achor',
    'How to Own The World: A Plain English Guide to Thinking Globally Investing Wisely by Andrew Craig',
    'How to Win Friends and Influence People by Dale Carnegie',
    'How to Write Copy That Sells: The Step-By-Step System for More Sales, to More Customers, More Often by Ray Edwards',
    'Indistractable: How to Control Your Attention and Choose Your Life by Nir Eyal',
    'I Will Teach You to Be Rich: No Guilt, No Excuses – Just a 6-Week Programme That Works by Ramit Sethi',
    'The Little Book of Yes: How to Win Friends, Boost Your Confidence and Persuade Others by Noah Goldstein',
    'Love and Respect: The Love She Most Desires; The Respect He Desperately Needs by Dr. Emerson Eggerichs',
    'Love Yourself Like Your Life Depends On It by Kamal Ravikant',
    'Magnetic Marketing: How To Attract A Flood Of New Customers That Pay, Stay, and Refer by Dan Kennedy',
    'Make Your Bed: Little Things That Can Change Your Life…And Maybe the World by William H. McRaven',
    'Managing Oneself by Peter Drucker',
    'Making It All Work: Winning at the Game of Work and the Business of Life by David Allen',
    'Mastermind Dinners: Build Lifelong Relationships by Connecting Experts, Influencers, and Linchpins by Jayson Gaignard',
    'Meditations by Marcus Aurelius',
    'Mindset: The New Psychology of Success by Carol Dweck',
    'Mini Habits: Smaller Habits, Bigger Results by Stephen Guise',
    'The Miracle Morning: The Not-So-Obvious Secret Guaranteed to Transform Your Life (Before 8AM) by Hal Elrod',
    'Mud, Sweat, and Tears: The Autobiography by Bear Grylls',
    'My Philosophy for Successful Living by Jim Rohn',
    'My Unfinished Business by Dan Kennedy',
    'Never Split the Difference: Negotiating As If Your Life Depends On It by Chris Voss',
    'No B.S. Time Management: The Ultimate No-Holds-Barred Kick-Butt Take-No-Prisoners Guide to Time Productivity and Sanity for Entrepreneurs by Dan Kennedy',
    'Notes From a Friend by Anthony Robbins',
    'The Obstacle Is the Way: The Timeless Art of Turning Trials into Triumph by Ryan Holiday',
    'Ogilvy on Advertising by David Ogilvy',
    'One Small Step Can Change Your Life: The Kaizen Way by Robert Maurer',
    'The ONE Thing: The Surprisingly Simple Truth Behind Extraordinary Results by Gary Keller',
    'On Writing: A Memoir of The Craft by Stephen King',
    'Peak: Secrets from the New Science of Expertise by Anders Ericsson',
    'Perennial Seller: The Art of Making and Marketing Work that Lasts by Ryan Holiday',
    'Positioning: The Battle for Your Mind by Al Ries and Jack Trout',
    'The Power of Moments: Why Certain Experiences Have Extraordinary Impact by Chip & Dan Heath',
    'The Practicing Mind: Developing Focus and Discipline in Your Life by Thomas M. Sterner',
    'The Psychology of Money: Timeless Lessons on Wealth, Greed, and Happiness by Morgan Housel',
    'Predictably Irrational: The Hidden Forces that Shape Our Decisions by Dan Ariely',
    'Reinvent Yourself by James Altucher',
    'Rejection Proof: How I Beat Fear and Became Invincible Through 100 Days of Rejection by Jia Jiang',
    'Rich Dad Poor Dad: What The Rich Teach Their Kids About Money That the Poor and Middle Class Do Not! by Robert T. Kiyosaki',
    'The Rich Employee by James Altucher',
    'Scrum: A Breathtakingly Brief and Agile Introduction by Chris Sims',
    'Secrets of The Millionaire Mind: Mastering The Inner Game of Wealth by T. Harv Eker',
    'Show Your Work!: 10 Ways to Share Your Creativity and Get Discovered by Austin Kleon',
    'Smartcuts: How Hackers, Innovators, and Icons Accelerate Success by Shane Snow',
    'Smarter Faster Better: The Secrets of Being Productive in Life and Business by Charles Duhigg',
    'Solving the Procrastination Puzzle: A Concise Guide to Strategies for Change by Timothy A. Pychyl',
    'Spark: 17 Steps That Will Boost Your Motivation for Anything by Dr. Jeremy Dean',
    'Start with Why: How Great Leaders Inspire Everyone to Take Action by Simon Sinek',
    'Steal Like an Artist: 10 Things Nobody Told You About Being Creative by Austin Kleon',
    'The Strangest Secret by Earl Nightingale',
    'The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life by Mark Manson',
    'The Success Principles: How to Get From Where You Are to Where You Want to Be by Jack Canfield',
    'Superhuman Social Skills: A Guide to Being Likeable, Winning Friends, and Building Your Social Circle by Tynan',
    'Super Thinking: The Big Book of Mental Models by Gabriel Weinberg and Lauren McCann',
    'Switch: How to Change Things When Change Is Hard by Chip & Dan Heath',
    'Thanks a Thousand: A Gratitude Journey by A.J. Jacobs',
    'Think and Grow Rich by Napoleon Hill',
    'This Is Where to Start: Find Superstar Mentors, Master All They Know, and Get Ahead in Your Career by Edward Druce',
    'Tiny Habits: The Small Changes That Change Everything by BJ Fogg',
    'Too Good to Leave, Too Bad to Stay: A Step-by-Step Guide to Help You Decide Whether to Stay In or Get Out of Your Relationship by Mira Kirshenbaum',
    'To Sell Is Human: The Surprising Truth About Persuading, Convincing, and Influencing Others by Daniel H Pink',
    'Tribes: We Need You to Lead Us by Seth Godin',
    'Triggers: Sparking Positive Change and Making It Last by Marshall Goldsmith and Mark Reiter',
    'Triggers: 30 Sales Tools You Can Use to Control the Mind of Your Prospect to Motivate, Influence and Persuade by Joe Sugarman',
    'Turning Pro: Tap Your Inner Power and Create Your Life’s Work by Steven Pressfield',
    'The War of Art: Break Through the Blocks and Win Your Inner Creative Battles by Steven Pressfield',
    'Unlimited Power: The New Science of Personal Achievement by Anthony Robbins',
    'When: The Scientific Secrets of Perfect Timing by Daniel H. Pink',
    'Who Moved My Cheese? An Amazing Way to Deal with Change in Your Work and in Your Life by Spencer Johnson',
    'Who Not How: The Formula to Achieve Bigger Goals Through Accelerating Teamwork by Benjamin Hardy',
    'Wooden: A Lifetime of Observations and Reflections On and Off the Court by John Wooden',
    'Work the System: The Simple Mechanics of Making More and Working Less by Sam Carpenter',
    'You Are a Writer (So Start Acting Like One) by Jeff Goins',
    'The Ultimate Sales Letter: Attract New Customers. Boost Your Sales. by Dan Kennedy',
    'Yes! 60 Secrets from The Science of Persuasion by Noah J. Goldstein, Steve J. Martin, and Robert B. Cialdini',
    'You Are Not So Smart: Why You Have Too Many Friends on Facebook, Why Your Memory Is Mostly Fiction, and 46 Other Ways You’re Deluding Yourself by David McRaney'
]

module.exports = {
    BOOKS
}